### ISSUE TITLE
clipCells causes 'cannot read property 0 of null'

### ISSUE THREAD

**Issue by twhitbeck** [d3/d3-voronoi#7] opened 2016-05-20 15:30 UTC
Repro: http://jsbin.com/cucerakofa/edit?js,console

Ran into this with certain datasets (most work fine). I tried debugging and don't have a clue what's going on, but

in the `clipCells` function, there's a chain of ternary operators ending with `null`. It's precisely this `null` (which is passed into `createBorderEdge` as the final argument creating an edge with a null point on the end) which is later being accessed for property `0` and is causing the TypeError.

**Comment by mbostock** [comment] 2016-05-20 17:49
I’ve reduced the test case down to four points that reliably reproduce the error. If I nudge any one of the points by a tiny amount, I’m able to compute the diagram successfully:

[![screen shot 2016-05-20 at 10 40 06 am](https://cloud.githubusercontent.com/assets/230541/15436534/43194f9a-1e77-11e6-8941-1ba9c679421a.png)](http://bl.ocks.org/mbostock/41354ca531df4c2bdd1e92d36af8802e)

So, this is probably because there are collinear or cocircular points, which have multiple valid Delaunay triangulations, as described in d3/d3#1895. This has been a problem in the past (see gorhill/Javascript-Voronoi#12). It was partially fixed by updating the port (d3/d3#1538), but I’m pretty sure we still don’t handle cocircular points correctly. As @jasondavies says, “I think a reasonable fix is to pick an arbitrary Delaunay triangulation in this situation.” But it’ll be some work to figure out how to actually implement that suggestion.

There was a pull request a while back that’s related (d3/d3#2238). But I haven’t had time to investigate it in detail and see if that’s an appropriate fix. I’ll try to look now.

**Comment by mbostock** [comment] 2016-05-20 17:55
Yeah, that fix just replaces the crash with an infinite loop, which is worse. 😁

**Comment by mbostock** [comment] 2016-05-20 19:27
Oops, I found something obviously wrong, and fixing it fixed this bug. I’m also testing some other changes which might make the code more reliable, but at least for your example, the above commit solves the problem.

**Closed** 2016-05-20 19:26 UTC

**Comment by mbostock** [comment] 2016-05-20 19:30
![screen shot 2016-05-20 at 12 29 37 pm](https://cloud.githubusercontent.com/assets/230541/15439687/9561c1b0-1e86-11e6-861e-a25f28b78ecf.png)

**Comment by twhitbeck** [comment] 2016-05-20 19:30
Excellent! thanks for looking into it

**Comment by mbostock** [comment] 2016-05-20 19:41
Fixed in 0.3.3.
