### ISSUE TITLE
Cell.js:75 Uncaught TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by AlexanderBollbach** [d3/d3-voronoi#30] opened 2018-07-25 01:03 UTC
I've been getting this error randomly when loading datasets into a plot.  I've spent a few days now trying to find the root cause of this.  I haven't been able to find any null values that I'm sending into the voronoi calculating code.  So right now my chart is crashing routinely and I don't know what to do.

**Comment by mbostock** [comment] 2018-07-25 14:20
This is probably a duplicate of #16 #12 and related to coincident, cocircular or collinear points. You might be able to workaround the issue by jittering the points as described in those issues. I would also take a look at [d3-delaunay](https://github.com/d3/d3-delaunay) as an alternative implementation.

**Closed by mbostock** 2018-07-25 14:20 UTC

**Comment by AlexanderBollbach** [comment] 2018-07-25 15:08
I finally stopped the crashes by de-duping my dataset.
